# Generated by Django 4.0 on 2021-12-22 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_alter_horoscope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horoscope_push_notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user_subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Horoscope_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('R', 'Received'), ('D', 'Deleted')], default='S', max_length=1)),
                ('horoscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.horoscope')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_horoscopes', to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Astrological_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('birth_place', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('starsign', models.CharField(choices=[('A', 'Aries'), ('T', 'Taurus'), ('G', 'Gemini'), ('C', 'Cancer'), ('L', 'Leo'), ('S', 'Sagittarius'), ('V', 'Virgo'), ('P', 'Pisces'), ('E', 'Aquarius'), ('S', 'Scorpio'), ('N', 'Capricorn'), ('U', 'Unspecified')], max_length=1)),
                ('planetary_affinity', models.CharField(choices=[('E', 'Earth'), ('M', 'Mars'), ('J', 'Jupiter'), ('S', 'Saturn'), ('U', 'Uranus'), ('N', 'Neptune'), ('P', 'Pluto'), ('V', 'Venus')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
